apiVersion: apps/v1
kind: Deployment
metadata:
   name: hellok8s
spec:
   replicas: 1
   selector:
      matchLabels:
        app: hellok8s
   template:
    metadata:
          labels:
            app: hellok8s
    spec:
      containers:
            - name: hellok8s
              image: nisarjava/hellok8s
              imagePullPolicy: Always
              ports:
               - containerPort: 8080
                 name: "http"
               - containerPort: 5005
                 name: "debug"
---
apiVersion: v1
kind: Service
metadata:
 name: hellok8s
spec:
 selector:
  app: hellok8s
 ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080   
 type: LoadBalancer                 
